# Generated by Django 5.0.6 on 2024-05-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_rawdata_numb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tenant', models.CharField(max_length=250)),
                ('ID', models.CharField(max_length=250)),
                ('Type', models.CharField(max_length=250)),
                ('Path', models.CharField(max_length=250)),
                ('Values', models.CharField(max_length=250)),
                ('ActivationInterval', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RatingPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.CharField(max_length=250)),
                ('DestinationRatesId', models.CharField(max_length=250)),
                ('TimingTag', models.CharField(max_length=250)),
                ('Weight', models.CharField(max_length=250)),
            ],
        ),
    ]
