export const FakeTable = [
  {
    accountName: "Alpha 1",
    trunks: [
      {
        accountName: "Alpha Trunk 1",
        carriers: [
          {
            accountName: "AlphaT Carr 1",
            accountID: "001",
            balance: "1000",
            asr: "0.1",
            sdp: "5",
            spent: "200",
            profit: "800",
            margin: "80%",
            sessions: "100",
            gainLoss: "20%",
          },
          {
            accountName: "AlphaT Carr 2",
            accountID: "001",
            balance: "1000",
            asr: "0.1",
            sdp: "5",
            spent: "200",
            profit: "800",
            margin: "80%",
            sessions: "100",
            gainLoss: "20%",
          },
        ],
        accountID: "001",
        balance: "1000",
        asr: "0.1",
        sdp: "5",
        spent: "200",
        profit: "800",
        margin: "80%",
        sessions: "100",
        gainLoss: "20%",
      },
      {
        accountName: "Alpha Trunk 2",
        carriers: [
          {
            accountName: "Alpha T2 Carr 1",
            accountID: "001",
            balance: "1000",
            asr: "0.1",
            sdp: "5",
            spent: "200",
            profit: "800",
            margin: "80%",
            sessions: "100",
            gainLoss: "20%",
          },
          {
            accountName: "Alpha T2 Carr 2",
            accountID: "001",
            balance: "1000",
            asr: "0.1",
            sdp: "5",
            spent: "200",
            profit: "800",
            margin: "80%",
            sessions: "100",
            gainLoss: "20%",
          },
        ],
        accountID: "001",
        balance: "1000",
        asr: "0.1",
        sdp: "5",
        spent: "200",
        profit: "800",
        margin: "80%",
        sessions: "100",
        gainLoss: "20%",
      },
    ],
    accountID: "001",
    balance: "1000",
    asr: "0.1",
    sdp: "5",
    spent: "200",
    profit: "800",
    margin: "80%",
    sessions: "100",
    gainLoss: "20%",
  },
  {
    accountName: "Alpha 2",
    trunks: [
      {
        accountName: "Alpha",
        carriers: [
          {
            accountName: "Alpha",
            accountID: "001",
            balance: "1000",
            asr: "0.1",
            sdp: "5",
            spent: "200",
            profit: "800",
            margin: "80%",
            sessions: "100",
            gainLoss: "20%",
          },
          {
            accountName: "Alpha",
            accountID: "001",
            balance: "1000",
            asr: "0.1",
            sdp: "5",
            spent: "200",
            profit: "800",
            margin: "80%",
            sessions: "100",
            gainLoss: "20%",
          },
        ],
        accountID: "001",
        balance: "1000",
        asr: "0.1",
        sdp: "5",
        spent: "200",
        profit: "800",
        margin: "80%",
        sessions: "100",
        gainLoss: "20%",
      },
      {
        accountName: "Alpha",
        carriers: [
          {
            accountName: "Alpha",
            accountID: "001",
            balance: "1000",
            asr: "0.1",
            sdp: "5",
            spent: "200",
            profit: "800",
            margin: "80%",
            sessions: "100",
            gainLoss: "20%",
          },
          {
            accountName: "Alpha",
            accountID: "001",
            balance: "1000",
            asr: "0.1",
            sdp: "5",
            spent: "200",
            profit: "800",
            margin: "80%",
            sessions: "100",
            gainLoss: "20%",
          },
        ],
        accountID: "001",
        balance: "1000",
        asr: "0.1",
        sdp: "5",
        spent: "200",
        profit: "800",
        margin: "80%",
        sessions: "100",
        gainLoss: "20%",
      },
    ],
    accountID: "001",
    balance: "1000",
    asr: "0.1",
    sdp: "5",
    spent: "200",
    profit: "800",
    margin: "80%",
    sessions: "100",
    gainLoss: "20%",
  },
];
